#pragma once

// Platform extensions
#ifndef PPOSIX_MAC_OS_EXTENSION_ENABLED
#define PPOSIX_MAC_OS_EXTENSION_ENABLED 0
#endif

#ifndef PPOSIX_FREE_BSD_EXTENSION_ENABLED
#define PPOSIX_FREE_BSD_EXTENSION_ENABLED 0
#endif

#ifndef PPOSIX_SOLARIS_EXTENSION_ENABLED
#define PPOSIX_SOLARIS_EXTENSION_ENABLED 0
#endif

#ifndef PPOSIX_LINUX_EXTENSION_ENABLED
#define PPOSIX_LINUX_EXTENSION_ENABLED 0
#endif
