#pragma once

// Platform extensions
#ifndef PPOSIX_MACOS_EXTENSION_ENABLED
#define PPOSIX_MACOS_EXTENSION_ENABLED 0
#endif

#ifndef PPOSIX_FREEBSD_EXTENSION_ENABLED
#define PPOSIX_FREEBSD_EXTENSION_ENABLED 0
#endif

#ifndef PPOSIX_OPENBSD_EXTENSION_ENABLED
#define PPOSIX_OPENBSD_EXTENSION_ENABLED 0
#endif

#ifndef PPOSIX_SOLARIS_EXTENSION_ENABLED
#define PPOSIX_SOLARIS_EXTENSION_ENABLED 0
#endif

#ifndef PPOSIX_LINUX_EXTENSION_ENABLED
#define PPOSIX_LINUX_EXTENSION_ENABLED 0
#endif

// POSIX extensions
#ifndef PPOSIX_REALTIME_EXTENSION_ENABLED
#define PPOSIX_REALTIME_EXTENSION_ENABLED 0
#endif
